### PR TITLE
bms_network_setup change

### PR DESCRIPTION
**Pull request by SebastianGode**

### CODE REVIEW

**Review by gtema — CHANGES_REQUESTED** [review]
I think branch master is wrong here

**Comment by SebastianGode** [comment]
Is it?
Because the main branch ist master:
https://github.com/opentelekomcloud/bms-network-setup

**Review by gtema — COMMENTED** [review]
you are right (on mobile it was hard to see). I am however wondering why do we need zuul here if there is not a single hint to zuul support by the repo

**Comment by SebastianGode** [comment]
GitStyring here was already set since before my time so merging anything isn't possible since several years now.
And having a pep8 check I guess isn't bad.
Theoretically we could also remove any protection completely, but running some pep8n checks shouldn't be an issue.

**Comment by gtema** [comment]
Merging would be possible by certain people only. It is just not used by anybody. I would suggest to instead make it an archive to indicate no work is happening there.
This project was never in hands of Ecosystem therefore no proper tests were ever implemented.

**Comment by SebastianGode** [comment]
There's an open PR which can't be merged, that's why I got the request to look at it: https://github.com/opentelekomcloud/bms-network-setup/pull/4
And they seem to use it, don't know whether archiving would be a good idea.

**Comment by gtema** [comment]
right, ok, didn't notice the PR.

Then we should disable branch protection (leave the teams part, but set branch protections to empty list)

**Comment by SebastianGode** [comment]
Okay removed the branch protection.

**Comment by SebastianGode** [comment]
This should be related: https://github.com/opentelekomcloud-infra/zuul-config/pull/138
And there also is an PR for the new team slug inside gitea.

**Review by gtema — APPROVED** [review]

**Pull request merged**
