### PR TITLE
Zuul integration

### PR DESCRIPTION
**Pull request by anton-sidelnikov**

### CODE REVIEW

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
@gtema, i want to run in .zuul check: ansible-playbook tests/basic.yml, how to do this?

**Comment by lego963** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Review by lego963 — APPROVED** [review]

**Pull request merged**
