### PR TITLE
Fix typo (looup -> lookup) & add missing true

### PR DESCRIPTION
**Pull request by berendt**
Signed-off-by: Christian Berendt <berendt@osism.tech>

### CODE REVIEW

**Comment by berendt** [comment]
Sorry for the noise. I tested badly.

**Review by gtema — APPROVED** [review]

**Comment by gtema** [comment]
> Sorry for the noise. I tested badly.

no problem. Sadly this part is not that easy to be tested through some form of unittests. If you have any ideas - welcome. The only reasonable chance I see is to have functional testing on dedicated test org

**Comment by gtema** [comment]
> Sorry for the noise. I tested badly.

no problem. Sadly this part is not that easy to be tested through some form of unittests. If you have any ideas - welcome. The only reasonable chance I see is to have functional testing on dedicated test org

**Comment by berendt** [comment]
A dedicated test org sounds like a good idea.

**Pull request merged**
